'use client'
import { useEffect,useState } from 'react'
import { stockLocationKey } from '../utils/stock-location-policy'
import type { InventoryReminder } from '../utils/inventory-reminder-policy'
export default function InventoryReminderSettings({selected,blocked}:{selected:string;blocked:boolean}){
 const [places,setPlaces]=useState<InventoryReminder[]>([]),[weeks,setWeeks]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const r=await fetch('/api/inventory/reminders',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setPlaces(d.locations||[]);if(d.warning)setMessage(d.warning);return d.locations||[]}
 useEffect(()=>{let active=true;load().then(rows=>{if(active){const p=rows.find((r:InventoryReminder)=>stockLocationKey(r.source,r.location_id)===selected);setWeeks(p?.interval_weeks?.toString()||'')}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[selected])
 const place=places.find(p=>stockLocationKey(p.source,p.location_id)===selected)
 async function save(action:'configure'|'complete'){if(!place)return;setBusy(true);setMessage('');try{const r=await fetch('/api/inventory/reminders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,source:place.source,location_id:place.location_id,...(action==='configure'?{interval_weeks:weeks===''?null:Number(weeks)}:{})})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage(action==='complete'?'Inventaire de tout ce lieu enregistré. Le prochain rappel repart de maintenant.':'Délai enregistré pour ce lieu.')}catch(e){setMessage(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}}
 return <section className="my-4 rounded-xl border bg-slate-50 p-3"><h2 className="font-bold">Rappel d’inventaire par lieu</h2>{place?<><p className="mt-2 text-sm">{place.last_completed_at?`Dernier inventaire complet : ${new Date(place.last_completed_at).toLocaleDateString('fr-FR')}`:'Aucun inventaire complet enregistré pour ce lieu.'}{place.due?' · Rappel arrivé à échéance':''}</p><label className="mt-3 block text-sm">Rappeler après combien de semaines ?<input aria-label="Délai inventaire en semaines" type="number" min="1" max="104" step="1" value={weeks} onChange={e=>setWeeks(e.target.value)} placeholder="Vide = désactivé" className="mt-1 w-full rounded-xl border p-3"/></label><button disabled={busy||weeks!==''&&(!Number.isInteger(Number(weeks))||Number(weeks)<1||Number(weeks)>104)} onClick={()=>void save('configure')} className="mt-2 min-h-11 rounded-xl border bg-white px-3 font-bold">Enregistrer le délai</button><p className="mt-2 text-xs">Vide désactive le rappel. Une modification de produit seule ne vaut pas inventaire du lieu.</p><button disabled={busy||blocked} onClick={()=>void save('complete')} className="mt-3 min-h-11 rounded-xl bg-emerald-700 px-3 font-bold text-white disabled:opacity-50">J’ai vérifié tout ce lieu</button>{blocked&&<p className="mt-1 text-xs">Enregistrer les corrections et effacer la recherche pour confirmer l’inventaire complet.</p>}</>:<p className="mt-2 text-sm">Choisir un lieu précis pour régler son délai et confirmer son inventaire complet.</p>}{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>
}
