'use client'
import Link from 'next/link'
import { useState } from 'react'
import type { ReadinessCheck } from '../utils/production-readiness-policy'
type Report={household:string;date:string;scope:string;readable:boolean;checks:ReadinessCheck[]}
export default function ProductionReadiness(){
 const [running,setRunning]=useState(false),[report,setReport]=useState<Report|null>(null),[error,setError]=useState('')
 async function run(){setRunning(true);setError('');setReport(null);try{const r=await fetch('/api/admin/readiness',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setReport(d)}catch(e){setError(e instanceof Error?e.message:'Vérification impossible.')}finally{setRunning(false)}}
 function download(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mealio-preproduction.json';a.click();URL.revokeObjectURL(url)}
 return <section aria-labelledby="preproduction-title" aria-busy={running} style={{backgroundColor:'#eef2ff',color:'#0f172a',borderColor:'#a5b4fc'}} className="my-4 rounded-xl border p-4"><h2 id="preproduction-title" style={{color:'#312e81'}} className="text-lg font-black">Avant la première mise en production</h2><p className="mt-3 text-sm">Ce contrôle lit les connexions, stocks, lieux, règles et tables du foyer connecté. Il ne crée aucun achat et ne remplace pas les essais du cycle complet.</p><button disabled={running} onClick={()=>void run()} style={{backgroundColor:'#4338ca',color:'#ffffff'}} className="mt-3 min-h-11 rounded-xl bg-indigo-700 px-3 font-bold text-white disabled:opacity-50">{running?'Vérification en cours…':'Vérifier les connexions et réglages'}</button>{running&&<p role="status" aria-live="polite" className="mt-2 text-sm">Lecture des DB en cours…</p>}{error&&<p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}{report&&<div className="mt-3 space-y-2"><p className="text-sm font-bold">{report.household} · {report.readable?'Lectures et réglages contrôlés — parcours réels à terminer':'Des points bloquants sont à corriger'}</p>{report.checks.map(c=><p key={c.id} className="rounded-lg bg-slate-50 p-2 text-sm"><b>{c.status==='pass'?'✓':c.status==='warning'?'À faire':'À corriger'} · {c.title}</b><br/>{c.detail}{c.href&&<> <Link href={c.href} className="font-bold underline">Ouvrir →</Link></>}</p>)}<button onClick={download} style={{backgroundColor:'#ffffff',color:'#0f172a',borderColor:'#64748b'}} className="min-h-11 rounded-xl border px-3 font-bold">Télécharger le bilan des connexions</button></div>}<details className="mt-4"><summary className="min-h-11 cursor-pointer font-bold">Les quatre contrôles à terminer</summary><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm"><li>Cycle réel : sur un foyer dédié finissant par -test ou _test, exécuter le cycle technique ci-dessous. Choisir une recette couvrant Frosti et Cellio, et au moins un produit en présence.</li><li>Deux foyers : vérifier que les listes, stocks et réglages restent privés ; confirmer qu’une correction commune de recette est réutilisée.</li><li>Fonctions récentes : vérifier une péremption connue dans Anti-gaspi, un signal Presque terminé, un rappel par lieu et l’alerte nouvelle recette réservée à KH.</li><li>Déploiement : lancer les tests, le typage et le build sur l’installation, puis vérifier le parcours sur smartphone.</li></ol></details><p className="mt-3 text-xs text-slate-500">Une lecture réussie ne prouve pas que les écritures ou les fonctions SQL ont été testées. Le cycle technique crée des données : il ne s’exécute jamais sur KH.</p></section>
}
