import test from 'node:test'
import assert from 'node:assert/strict'
import { SCREEN_HELP,screenHelp } from '../../app/utils/contextual-help'
import { GET as readiness } from '../../app/api/admin/readiness/route'
import { GET as stocks } from '../../app/api/stock/route'
import { PATCH as pantryUpdate } from '../../app/api/admin/pantry/route'
import { loadReferenceData,resolveStockIngredientId } from '../../app/utils/matcher'
import { createSessionValue } from '../../app/utils/auth-server'
import { makeReferenceData } from '../../scripts/matcher-test-fixtures'
// @ts-expect-error test doubles
import { setDbResolver,calls } from '../../test-support/db.mjs'
// @ts-expect-error test doubles
import { setCookies } from '../../test-support/headers.mjs'
const ingredient='12345678-1234-1234-1234-123456789abc'
function setup(missing=false){const ref=makeReferenceData();let policyAlpha=true;setDbResolver((c:any)=>{
 if(c.table==='shopping_purchase_events'&&c.filters.some((f:any)=>f[1]==='shopping_list_id'))return {data:null,error:{message:'column shopping_purchase_events.shopping_list_id does not exist'}}
 const rows:any=c.table==='app_users'?['Alpha','Beta'].map(username=>({id:c.source+'-'+username,username})):c.table==='items'?['Alpha','Beta'].map(username=>({id:'stock-'+username,user_id:c.source+'-'+username,produit:'Produit commun',qte:username==='Alpha'?1:9,unite:'Gramme',categorie:'Test',congelo_id:'f-'+username,cellar_id:'c-'+username})):c.table==='freezers'||c.table==='cellars'?['Alpha','Beta'].map(username=>({id:(c.table==='freezers'?'f-':'c-')+username,user_id:c.source+'-'+username,name:username+' lieu'})):c.table==='storage_routing_rules'?['Alpha','Beta'].map(username=>({id:username,user_id:c.source+'-'+username,rule_type:c.source==='frosti'?'default_freezer':'default',freezer_id:'f-'+username,cellar_id:'c-'+username,priority:50,is_active:true})):c.table==='official_ingredients'?[...ref.officialList,{id:ingredient,nom:'Produit commun',unite_reference:'Gramme',categorie:'Test',rayon:null}]:c.table==='ingredient_synonyms'?[{mot_recette:'Libellé commun',ingredient_id:ingredient}]:c.table==='unit_mappings'?ref.unitMappings:c.table==='household_pantry_products'?['Alpha','Beta'].map(username=>({user_id:username,ingredient_id:ingredient,default_quantity:250,default_unit:'Gramme',enabled:username==='Alpha'?policyAlpha:false})):c.table==='recipes'?[{id:'recipe',title:'Recette commune'}]:[]
 if(missing&&c.table==='household_inventory_reminders')return {data:null,error:{code:'42P01',message:'Table absente'}}
 if(c.action==='upsert'&&c.table==='household_pantry_products'){if(c.payload.user_id==='Alpha')policyAlpha=c.payload.enabled;return{data:c.payload,error:null}}
 const filtered=rows.filter((r:any)=>c.filters.every(([op,key,value]:any[])=>op==='in'?value.includes(r[key]):op==='neq'?r[key]!==value:r[key]===value));return {data:c.single?filtered[0]||null:filtered,error:null}
 })}
function session(username:string){process.env.MEALIO_SESSION_SECRET='preproduction-secret';setCookies({mealio_session:createSessionValue(username,'frosti-'+username)})}
test('aide : tous les écrans fonctionnels et liens locaux, texte court',()=>{const pages=['/','/login','/planning','/courses','/stock','/replenishment','/anti-gaspi','/inventaire','/purchases','/admin','/admin/storage','/admin/storage/pending','/admin/storage/test','/admin/pantry','/admin/data','/admin/ingredients','/admin/recipes','/admin/integration','/matcher','/matcher/correction'];for(const route of pages){const h=screenHelp(route)!;assert.ok(h,route);assert.ok(h.logic.length<350&&h.action.length<350,route);assert.ok(screenHelp(h.next.href.split(/[?#]/)[0]));if(h.extra)assert.ok(screenHelp(h.extra.href.split(/[?#]/)[0]))}assert.equal(screenHelp('/point-frigo'),SCREEN_HELP['/inventaire']);assert.equal(screenHelp('/inconnue'),null)})
test('diagnostic : authentification avant toute lecture',async()=>{setCookies({});setup();assert.equal((await readiness()).status,401);assert.equal(calls.length,0)})
test('diagnostic : lecture seule, aucun Claude, succès des lectures différent de production validée',async()=>{session('Alpha');setup();globalThis.fetch=async()=>{throw Error('Claude interdit')};const r=await readiness();assert.equal(r.status,200);const body=await r.json();assert.equal(body.household,'Alpha');assert.equal(body.readable,true);assert.equal(body.checks.filter((c:any)=>c.status==='warning').length,2);assert.ok(calls.every((c:any)=>c.action==='select'));const historyCall=calls.find((c:any)=>c.table==='shopping_purchase_events');assert.ok(historyCall.filters.some((f:any)=>f[0]==='in'&&f[1]==='list_id'));const owned=calls.filter((c:any)=>['items','storage_routing_rules','freezers','cellars'].includes(c.table));assert.ok(owned.every((c:any)=>c.filters.some((f:any)=>f[1]==='user_id'&&f[2]===c.source+'-Alpha')))})
test('diagnostic : migration absente signalée en échec, pas de faux feu vert',async()=>{session('Alpha');setup(true);const r=await readiness();const b=await r.json();assert.equal(b.readable,false);assert.ok(b.checks.some((c:any)=>c.status==='fail'&&/rappel|household_inventory/i.test(c.title)));assert.ok(calls.every((c:any)=>c.action==='select'))})
test('deux foyers : stocks et présence privés, correspondance officielle commune',async()=>{setup();session('Alpha');let b=await (await stocks()).json();assert.ok(b.items.length===2&&b.items.every((i:any)=>i.id==='stock-Alpha'&&i.qte===1&&i.pantry_ingredient_id===ingredient));session('Beta');b=await (await stocks()).json();assert.ok(b.items.length===2&&b.items.every((i:any)=>i.id==='stock-Beta'&&i.qte===9&&i.pantry_ingredient_id===null));const a=await loadReferenceData('Alpha'),beta=await loadReferenceData('Beta');assert.equal(resolveStockIngredientId(a,'Libellé commun'),ingredient);assert.equal(resolveStockIngredientId(beta,'Libellé commun'),ingredient);session('Alpha');const patch=await pantryUpdate(new Request('http://local/api/admin/pantry',{method:'PATCH',body:JSON.stringify({user_id:'Beta',ingredient_id:ingredient,enabled:false,default_quantity:500,default_unit:'Gramme'})}));assert.equal(patch.status,200);assert.equal(calls.find((c:any)=>c.action==='upsert').payload.user_id,'Alpha');session('Beta');assert.equal((await loadReferenceData('Beta')).pantryProducts?.get(ingredient)?.enabled,false);setCookies({})})
