import test from 'node:test'
import assert from 'node:assert/strict'
import { makeReferenceData } from '../../scripts/matcher-test-fixtures'
import { cleanText,resolveRecipeIngredients,compareToStock,aggregateRequirements,createMatcherTrace,convertQuantityToUnit } from '../../app/utils/matcher'
import { quantitativeRecipeEstimates } from '../../app/utils/recipe-test-estimates'
import { PATCH as togglePreparation } from '../../app/api/admin/preparations/route'
import { loadIngredientPreparations } from '../../app/utils/ingredient-preparations-server'
import { createSessionValue } from '../../app/utils/auth-server'
// @ts-expect-error local session double
import { setCookies } from '../../test-support/headers.mjs'
import { stockAnalysisKey } from '../../app/utils/stock-analysis-cache'
// @ts-expect-error local HTTP/DB double
import { setDbResolver } from '../../test-support/db.mjs'
function fixture(){const ref=structuredClone(makeReferenceData());for(const [name,unit] of [['Mayonnaise','Gramme'],['Œuf (poule)','Pièce'],["Huile d’olive",'Millilitre'],['Poivre noir','Gramme'],['Poulet entier','Gramme'],['Cuisse de poulet','Gramme']] as const){const i={id:name,nom:name,unite_reference:unit,rayon:null,categorie:'Test',default_storage:'frosti'};ref.officialList.push(i);ref.officialById.set(i.id,i);ref.officialPrepared.push({item:i,normalized:cleanText(name),tokens:cleanText(name).split(' ')})}ref.pantryProducts=new Map([['Huile d’olive',{ingredient_id:'Huile d’olive',default_quantity:1000,default_unit:'Millilitre',enabled:true}],['Poivre noir',{ingredient_id:'Poivre noir',default_quantity:250,default_unit:'Gramme',enabled:true}],['test-sel',{ingredient_id:'test-sel',default_quantity:250,default_unit:'Gramme',enabled:true}]]);return ref}
test('estimations : mode réel du foyer et nom original, pas catégorie globale',()=>{const inputs=[{name:'Sel',qty:1,unit:'g',quantityEstimated:true},{name:'Farine',qty:100,unit:'g',quantityEstimated:true}];assert.deepEqual(quantitativeRecipeEstimates(inputs,[{source_ingredient_name:'Sel',quantity_mode:'presence'},{source_ingredient_name:'Farine',quantity_mode:'quantity'}]).map(i=>i.name),['Farine']);assert.equal(quantitativeRecipeEstimates(inputs,[{source_ingredient_name:'Sel',quantity_mode:'quantity'}]).length,1)})
test('mayonnaise maison : un oeuf, trois présences, pas de besoin mayonnaise',async()=>{const ref=fixture();ref.ingredientPreparations=new Map([['Mayonnaise',{ingredient_id:'Mayonnaise',enabled:true,components:[{name:'Œuf (poule)',qty:1,unit:'Pièce'},{name:'Huile d’olive',qty:0,unit:'Millilitre'},{name:'Sel fin',qty:0,unit:'Gramme'},{name:'Poivre noir',qty:0,unit:'Gramme'}]}]]);const rows=await resolveRecipeIngredients([{name:'Mayonnaise',qty:20,unit:'g'}],ref,'r','r');assert.equal(rows.length,4);assert.equal(rows.filter(r=>r.quantity_mode==='quantity').length,1);assert.equal(rows.find(r=>r.produit==='Œuf (poule)')?.qte,1);assert.ok(rows.every(r=>!r.quantity_unknown&&!r.needs_review));const doubled=await resolveRecipeIngredients([{name:'Mayonnaise',qty:20,unit:'g'}],ref,'r','r',2);assert.equal(doubled.find(r=>r.produit==='Œuf (poule)')?.qte,2);const other=fixture();assert.equal((await resolveRecipeIngredients([{name:'Mayonnaise',qty:20,unit:'g'}],other,'r','r'))[0].produit,'Mayonnaise');ref.ingredientPreparations.get('Mayonnaise')!.enabled=false;assert.equal((await resolveRecipeIngredients([{name:'Mayonnaise',qty:20,unit:'g'}],ref,'r','r'))[0].produit,'Mayonnaise')})
test('poulet entier : aucune cuisse ne couvre le besoin, aucun appel Claude',async()=>{const ref=fixture();const resolved=await resolveRecipeIngredients([{name:'Poulet entier',qty:1000,unit:'g'}],ref,'r','r');const trace=createMatcherTrace('Poulet entier');const rows=await compareToStock(aggregateRequirements([resolved]),[{id:'stock',produit:'Cuisse de poulet',qte:2000,unite:'g'}],ref,trace,{memory:new Map(),exclusions:new Set(),persistMemory:false});assert.equal(rows[0].qte_stock,0);assert.equal(rows[0].qte_a_acheter,1000);assert.equal(rows[0].needs_review,false);assert.equal(trace.claudeCalls,0)})
test('pots : unité de conditionnement et moyenne par ingrédient',()=>{const ref=fixture();ref.unitMappings.push({unite:'Pot 250mL',abreviation:null,type_unite:'divers',multiplicateur:1});ref.densities.push({ingredient_id:'Mayonnaise',unite:'Pot 250mL',poids_g_approx:145});assert.equal(convertQuantityToUnit(ref,'Mayonnaise',2,'Pot 250mL','Gramme')?.qty,290);assert.equal(convertQuantityToUnit(ref,'Poulet entier',2,'Pot 250mL','Gramme'),null)})
test('mémoire analyse : lot neuf et quantité changée ne changent pas le cas ; candidat différent le change',()=>{const a=stockAnalysisKey('id','ref',[{item:{produit:'Produit A',source:'frosti'}}]);assert.equal(a,stockAnalysisKey('id','ref',[{item:{produit:'Produit A',source:'frosti'}},{item:{produit:'Produit A',source:'frosti'}}]));assert.notEqual(a,stockAnalysisKey('id','ref',[{item:{produit:'Produit B',source:'frosti'}}]));assert.notEqual(a,stockAnalysisKey('id','ref2',[{item:{produit:'Produit A',source:'frosti'}}]))})
test('proposition en attente mémorisée : deuxième passage et nouveau lot sans Claude ; pas de déduction',async()=>{const ref=fixture();let stored:any=null;setDbResolver((call:any)=>({data:call.table==='matcher_stock_analysis_cache'?(call.action==='upsert'?(stored=call.payload,null):stored):call.single?null:[],error:null}));process.env.ANTHROPIC_API_KEY='local-test';let count=0;globalThis.fetch=async()=>{count++;return Response.json({content:[{type:'text',text:JSON.stringify({match:'s1',confidence:0.7,reason:'Proposition'})}]})};const resolved=await resolveRecipeIngredients([{name:'Poulet entier',qty:1000,unit:'g'}],ref,'r','r');const context={memory:new Map(),exclusions:new Set<string>(),persistMemory:true};const stock=[{id:'s1',produit:'Poulet entier préparé spécial au marché recette artisanale' ,qte:2,unite:'Pièce',source:'frosti'}];const first=await compareToStock(aggregateRequirements([resolved]),stock,ref,undefined,context);assert.equal(first[0].qte_stock,0);assert.equal(first[0].needs_review,true);const second=await compareToStock(aggregateRequirements([resolved]),[{...stock[0],id:'s2',qte:3}],ref,undefined,context);assert.equal(second[0].needs_review,true);assert.equal(second[0].qte_stock,0);assert.equal(count,1)})
test('réponse AUCUN : mémorisée sans fausse association ; indisponibilité non mémorisée',async()=>{const ref=fixture();let stored:any=null;setDbResolver((call:any)=>({data:call.table==='matcher_stock_analysis_cache'?(call.action==='upsert'?(stored=call.payload,null):stored):call.single?null:[],error:null}));process.env.ANTHROPIC_API_KEY='local-test';let count=0;globalThis.fetch=async()=>{count++;return Response.json({content:[{type:'text',text:'{"match":"AUCUN","confidence":0,"reason":"Aucun produit adapté"}'}]})};const resolved=await resolveRecipeIngredients([{name:'Poulet entier',qty:1000,unit:'g'}],ref,'r','r');const ctx={memory:new Map(),exclusions:new Set<string>(),persistMemory:true};const stock=[{id:'s1',produit:'Poulet entier préparé spécial au marché recette artisanale',qte:2,unite:'Pièce',source:'frosti'}];const first=await compareToStock(aggregateRequirements([resolved]),stock,ref,undefined,ctx);assert.equal(first[0].needs_review,false);assert.equal(first[0].qte_a_acheter,1000);await compareToStock(aggregateRequirements([resolved]),stock,ref,undefined,ctx);assert.equal(count,1);stored=null;globalThis.fetch=async()=>Response.json({error:'Service unavailable'},{status:503});const unavailable=await compareToStock(aggregateRequirements([resolved]),stock,ref,undefined,ctx);assert.equal(unavailable[0].needs_review,true);assert.equal(stored,null)})

test('préparation : authentification et choix limité au foyer connecté',async()=>{process.env.MEALIO_SESSION_SECRET='test-preparation-secret-----------------';setCookies({});const request=()=>new Request('http://local/api/admin/preparations',{method:'PATCH',body:JSON.stringify({ingredient_id:'m',enabled:false})});assert.equal((await togglePreparation(request())).status,401);setCookies({mealio_session:createSessionValue('KH','uuid-kh')});let update:any;setDbResolver((c:any)=>{if(c.action==='update')update=c;return{data:{ingredient_id:'m',enabled:false},error:null}});assert.equal((await togglePreparation(request())).status,200);assert.ok(update.filters.some((f:any)=>f[1]==='user_id'&&f[2]==='KH'));let read:any;setDbResolver((c:any)=>{read=c;return{data:[],error:null}});await loadIngredientPreparations('Autre');assert.ok(read.filters.some((f:any)=>f[1]==='user_id'&&f[2]==='Autre'));setCookies({})})
