import test from 'node:test'
import assert from 'node:assert/strict'
import { expiryDay,expiryDays,parisDate } from '../../app/utils/expiry-policy'
import { inventoryDeadline } from '../../app/utils/inventory-reminder-policy'
import { GET as remindersGET,PATCH as remindersPATCH } from '../../app/api/inventory/reminders/route'
import { getAntiGaspiTonight } from '../../app/utils/anti-gaspi-server'
import { getFrostiStock } from '../../app/utils/household-server'
import { makeReferenceData } from '../../scripts/matcher-test-fixtures'
import { cleanText,loadReferenceData,resolveRecipeIngredients,aggregateRequirements,compareToStock } from '../../app/utils/matcher'
import { quantitativeRecipeEstimates } from '../../app/utils/recipe-test-estimates'
import { createSessionValue } from '../../app/utils/auth-server'
// @ts-expect-error local DB double
import { setDbResolver,calls } from '../../test-support/db.mjs'
// @ts-expect-error local session double
import { setCookies } from '../../test-support/headers.mjs'
const place='12345678-1234-1234-1234-123456789abc'
function session(){process.env.MEALIO_SESSION_SECRET='inventory-secret';setCookies({mealio_session:createSessionValue('KH','kh-id')})}
const reference=()=>{const ref=structuredClone(makeReferenceData());for(const nom of ['Persil plat','Ciboulette']){const i={id:nom,nom,unite_reference:'Gramme',rayon:null,categorie:'Herbes',default_storage:'cellio'};ref.officialList.push(i);ref.officialById.set(nom,i);ref.officialPrepared.push({item:i,normalized:cleanText(nom),tokens:cleanText(nom).split(' ')})}return ref}
function setup(stock:any[]=[],options:{override?:boolean;missing?:boolean;reminders?:any[]}={}){const ref=reference();setDbResolver((c:any)=>{
 if(c.table==='app_users')return {data:{id:`${c.source}-user`,username:'KH'},error:null}
 if(c.table==='freezers')return {data:[{id:place,name:'Frigo'}],error:null}
 if(c.table==='cellars')return {data:[],error:null}
 if(c.table==='household_inventory_reminders')return options.missing?{data:null,error:{code:'42P01',message:'missing'}}:{data:options.reminders||[],error:null}
 if(c.table==='items')return {data:stock.filter(i=>i.source===c.source),error:null}
 if(c.table==='household_pantry_products')return {data:[{ingredient_id:'Persil plat',enabled:options.override!==false,default_quantity:1,default_unit:'Bouquet'},{ingredient_id:'Ciboulette',enabled:true,default_quantity:1,default_unit:'Bouquet'}],error:null}
 const tables:any={official_ingredients:ref.officialList,ingredient_synonyms:[...ref.synonymMap].map(([mot_recette,ingredient_id])=>({mot_recette,ingredient_id})),unit_mappings:ref.unitMappings,ingredient_densities:ref.densities};return {data:c.single?null:tables[c.table]||[],error:null}
 })}
const patch=(body:unknown)=>remindersPATCH(new Request('http://local/api/inventory/reminders',{method:'PATCH',body:JSON.stringify(body)}))
test('péremption : dates, timestamps Paris, dates impossibles et borne J+3',()=>{assert.equal(expiryDay('2026-10-08'),'2026-10-08');assert.equal(expiryDay('2026-10-08T22:30:00Z'),'2026-10-09');assert.equal(expiryDay('2026-10-08 12:30:00'),'2026-10-08');for(const value of ['2026-02-30','2026-10-08T99:00:00','inconnue',null])assert.equal(expiryDay(value),null);assert.equal(expiryDays('2026-10-11T10:00:00Z','2026-10-08'),3);assert.equal(expiryDays('2026-10-12','2026-10-08'),4);assert.equal(expiryDays('2026-10-07','2026-10-08'),-1)})
test('anti-gaspi réel : timestamps retenus, manque de dates diagnostiqué, zéro et vins exclus',async()=>{session();const today=parisDate();const day=(n:number)=>new Date(Date.parse(today+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);const item=(id:string,date:string|null,qte=1,produit='Persil plat')=>({id,produit,qte,unite:'g',categorie:'Herbes',source:'frosti',date_peremption:date});setup([item('due',day(3)+'T12:00:00Z'),item('late',day(-1)),item('future',day(4)),item('missing',null),item('bad','2026-02-30'),item('empty',day(0),0),item('wine',day(0),1,'Vin rouge')]);const result=await getAntiGaspiTonight('KH');assert.deepEqual(result.urgentStock.map(i=>i.id),['late','due']);assert.deepEqual(result.expiryDiagnostic,{available:6,eligible:5,dated:3,missing:1,invalid:1,expired:1,today,horizonDays:3});assert.equal((result.availableStock[0] as any).quantity_mode,'presence')})
test('présence : pipeline DB → matcher → stock → estimations, même unité recette inconnue',async()=>{session();setup();const ref=await loadReferenceData('KH');const ingredients=[{name:'Persil plat',qty:25,unit:'une poignée inconnue',quantityEstimated:true},{name:'Ciboulette',qty:5,unit:'g',quantityEstimated:true}];const resolved=await resolveRecipeIngredients(ingredients,ref,'r','r');assert.ok(resolved.every(i=>i.quantity_mode==='presence'&&i.unite==='Présence'&&i.qte===1));assert.deepEqual(quantitativeRecipeEstimates(ingredients,resolved),[]);const compared=await compareToStock(aggregateRequirements([resolved]),[{id:'s',produit:'Persil plat',qte:1,unite:'Bouquet',source:'frosti'}],ref);assert.equal(compared.find(i=>i.produit==='Persil plat')?.qte_a_acheter,0);setup([],{override:false});const quantitative=await resolveRecipeIngredients([{name:'Persil plat',qty:25,unit:'g'}],await loadReferenceData('KH'),'r','r');assert.equal(quantitativeRecipeEstimates([{name:'Persil plat',qty:25,unit:'g',quantityEstimated:true}],quantitative).length,1);assert.ok(calls.filter((c:any)=>c.table==='household_pantry_products').every((c:any)=>c.filters.some((f:any)=>f[1]==='user_id'&&f[2]==='KH')))})
test('stocks : péremptions de la seconde page non perdues au-delà de 500 lignes',async()=>{setDbResolver((c:any)=>({data:c.range[0]===0?Array.from({length:500},(_,n)=>({id:String(n),produit:'P',qte:1})): [{id:'last',produit:'Dernier',qte:1,date_peremption:'2026-10-08T12:00:00Z'}],error:null}));const stock=await getFrostiStock('owned');assert.equal(stock.length,501);assert.equal(stock[500].date_peremption,'2026-10-08T12:00:00Z');assert.deepEqual(calls.map((c:any)=>c.range),[[0,499],[500,999]])})
test('rappel : désactivation, échéance exacte, dernier inventaire complet prioritaire',()=>{const now=Date.parse('2026-10-08T12:00:00Z');const r={interval_weeks:2,last_completed_at:null,configured_at:'2026-09-24T12:00:00Z'};assert.equal(inventoryDeadline(r,now).due,true);assert.equal(inventoryDeadline(r,now-1).due,false);assert.equal(inventoryDeadline({...r,interval_weeks:null},now).due,false);assert.equal(inventoryDeadline({...r,last_completed_at:'2026-10-07T12:00:00Z'},now).due,false)})
test('rappel API : auth, lieu privé, délais invalides, écriture atomique et table manquante',async()=>{setCookies({});assert.equal((await remindersGET()).status,401);session();setup([],{missing:true});assert.match((await (await remindersGET()).json()).warning,/SQL Mealio/);setup();assert.equal((await patch({action:'configure',source:'cellio',location_id:place,interval_weeks:4})).status,403);assert.equal((await patch({action:'configure',source:'frosti',location_id:place,interval_weeks:0})).status,400);assert.equal((await patch({action:'configure',source:'frosti',location_id:place,interval_weeks:4})).status,200);const rpc=calls.find((c:any)=>c.action==='rpc');assert.equal(rpc.payload.p_user_id,'KH');assert.equal(rpc.payload.p_interval_weeks,4);assert.equal((await patch({action:'complete',source:'frosti',location_id:place})).status,200);assert.equal(calls.filter((c:any)=>c.action==='rpc')[1].payload.p_action,'complete');setCookies({})})
