export type ScreenHelp={title:string;position:string;logic:string;action:string;next:{href:string;label:string};extra?:{href:string;label:string}}
export const SCREEN_HELP:Record<string,ScreenHelp>={
 '/':{title:'Accueil',position:'Vue d’ensemble du foyer',logic:'Prévois les repas, achète ce qui manque, range les achats dans les lieux précis puis confirme les repas consommés.',action:'Commence par Planning pour organiser les repas, ou Courses pour reprendre ta liste active.',next:{href:'/planning',label:'Ouvrir le Planning'},extra:{href:'/courses',label:'Reprendre les Courses'}},
 '/login':{title:'Se connecter',position:'Entrer dans son foyer',logic:'Le même compte est partagé par les membres du foyer. Son nom relie les stocks Frosti et Cellio.',action:'Utilise les identifiants de ton foyer. Tu retrouveras son planning et ses courses.',next:{href:'/planning',label:'Planning'}},
 '/planning':{title:'Planning',position:'1/4 · Prévoir les repas',logic:'Les recettes et portions prévues déterminent les besoins. La consommation est confirmée séparément ; les produits en présence ne sont pas déduits.',action:'Ajoute tes repas et ajuste leurs portions, puis génère les courses de la période.',next:{href:'/courses',label:'Passer aux Courses'}},
 '/courses':{title:'Courses',position:'2/4 · Acheter ce qui manque',logic:'Mealio compare les besoins au stock. En présence, il vérifie seulement s’il reste le produit et propose son format d’achat si absent.',action:'Clique sur un point à vérifier pour le corriger. En magasin, indique les achats réels ; range-les et termine la liste.',next:{href:'/admin/storage/pending',label:'Voir les articles à ranger'},extra:{href:'/planning',label:'Revoir le planning'}},
 '/stock':{title:'Stocks',position:'Après le rangement · Voir ce qui est disponible',logic:'Les stocks viennent de Frosti et Cellio, avec leurs lieux précis. Présence signifie disponible ou absent, sans dose à compter.',action:'Filtre par lieu ou recherche un produit. « Presque terminé » propose un réappro sans changer le stock.',next:{href:'/inventaire',label:'Corriger le stock'},extra:{href:'/anti-gaspi',label:'Utiliser les produits urgents'}},
 '/replenishment':{title:'Réapprovisionnements',position:'Préparer les prochains achats',logic:'Seuils, échéances, signaux « Presque terminé » et historiques proposent des achats. Rien n’est ajouté sans ton choix.',action:'Vérifie le format proposé, puis ajoute le produit aux courses. Ajuste les règles si nécessaire.',next:{href:'/courses',label:'Ouvrir les Courses'},extra:{href:'/admin/pantry',label:'Régler la présence et les formats'}},
 '/anti-gaspi':{title:'Anti-gaspi',position:'Choisir un repas à partir du stock',logic:'Les dates dépassées et celles d’ici 3 jours sont signalées. Sans date exploitable, Mealio ne peut pas juger l’urgence.',action:'Sélectionne des produits : OU accepte au moins un produit, ET exige tous les produits. Choisis ensuite une recette.',next:{href:'/planning',label:'Planifier un repas'},extra:{href:'/inventaire',label:'Vérifier les stocks et leurs lieux'}},
 '/inventaire':{title:'Inventaire',position:'Fiabiliser les stocks avant les prochains repas',logic:'Une correction met à jour Frosti ou Cellio. Pour un produit en présence, indique seulement s’il en reste.',action:'Recherche partout ou choisis un lieu. Enregistre les corrections ; « J’ai vérifié tout ce lieu » confirme un inventaire complet et relance son délai de rappel.',next:{href:'/stock',label:'Revoir les Stocks'}},
 '/purchases':{title:'Historique des achats',position:'Après les courses · Retrouver les achats',logic:'L’historique permet de vérifier les achats et aide à proposer les réappros des produits en présence. Une seule date ne suffit pas à apprendre une fréquence.',action:'Filtre pour retrouver un achat. Pour vérifier ce qu’il reste maintenant, consulte le stock.',next:{href:'/stock',label:'Voir les Stocks'},extra:{href:'/replenishment',label:'Voir les réapprovisionnements'}},
 '/admin':{title:'Réglages du foyer',position:'Préparer et entretenir Mealio',logic:'Rangement, présence et réappros sont propres au foyer. Les recettes et le référentiel sont communs.',action:'Utilise les réglages du foyer au quotidien. Ouvre les outils avancés pour les corrections et tests.',next:{href:'/admin/storage/pending',label:'Articles à ranger'},extra:{href:'/admin/integration',label:'Tests et préparation à la production'}},
 '/admin/storage/pending':{title:'Articles à ranger',position:'3/4 · Ranger les achats',logic:'Un achat peut attendre un ingrédient officiel ou un lieu précis. Le rangement ajoute le stock dans Frosti ou Cellio.',action:'Ouvre la correction indiquée, puis relance le rangement. Une recette corrigée exige aussi de régénérer ses courses.',next:{href:'/stock',label:'Vérifier les stocks rangés'},extra:{href:'/admin/storage',label:'Régler les lieux par défaut'}},
 '/admin/storage':{title:'Règles de rangement',position:'Définir où vont les achats',logic:'Les règles de ce foyer désignent des lieux précis. Les exceptions ingrédient permettent de distinguer un produit de sa catégorie.',action:'Choisis le type de règle, son lieu et sa priorité. Utilise le test de rangement pour vérifier le résultat avant les prochains achats.',next:{href:'/admin/storage/test',label:'Tester une règle'},extra:{href:'/admin/storage/pending',label:'Relancer les articles en attente'}},
 '/admin/storage/test':{title:'Test de rangement',position:'Vérifier la destination d’un achat',logic:'Ce test explique quelle règle sélectionne un lieu pour le produit, sans y ranger un achat.',action:'Choisis un produit et vérifie la destination. Si elle ne convient pas, corrige sa règle.',next:{href:'/admin/storage',label:'Modifier les règles'}},
 '/admin/pantry':{title:'Épicerie et présence',position:'Choisir comment le foyer suit ses produits',logic:'Présence : il en reste ou non. Quantitatif : les doses sont calculées. Le format d’achat est distinct de la dose consommée.',action:'Choisis le mode et le format acheté. En quittant la présence, choisis l’unité et vérifie les quantités réelles en stock.',next:{href:'/inventaire',label:'Vérifier les quantités réelles'},extra:{href:'/courses',label:'Recalculer les Courses'}},
 '/admin/data':{title:'Tables et relations',position:'Outils avancés · Comprendre les données',logic:'Cet écran permet de consulter les données et les liens utilisés par Mealio. Les réglages privés et communs ont des rôles distincts.',action:'Pour corriger un produit, privilégie son écran dédié plutôt que de modifier des données sans connaître leur rôle.',next:{href:'/admin/ingredients',label:'Ouvrir le référentiel'},extra:{href:'/admin',label:'Revenir aux réglages'}},
 '/admin/ingredients':{title:'Référentiel ingrédients',position:'Outils avancés · Corriger le savoir commun',logic:'Un synonyme associe un libellé à un ingrédient. Une équivalence convertit une quantité. Une proposition IA demande confirmation avant déduction.',action:'Choisis l’ingrédient exact, ajoute un synonyme ou une équivalence, puis reteste. Garde des ingrédients distincts quand ils ne sont pas interchangeables.',next:{href:'/admin/integration',label:'Retester les recettes'},extra:{href:'/admin/pantry',label:'Régler le suivi du foyer'}},
 '/admin/recipes':{title:'Correction d’une recette',position:'Outils avancés · Préciser les besoins',logic:'Les doses concernent les portions de base. « Estimation » signale une dose proposée ou incertaine ; en présence, elle n’a pas à être confirmée pour ce foyer.',action:'Si une dose convient, confirme l’estimation puis enregistre. Sinon ajuste-la. Les corrections de recette sont communes à tous les foyers.',next:{href:'/admin/integration#corrections',label:'Revenir à la liste des corrections'},extra:{href:'/courses',label:'Recalculer les Courses'}},
 '/admin/integration':{title:'Tests des recettes',position:'Outils avancés · Vérifier avant utilisation',logic:'L’analyse teste les besoins avec ton stock, sans créer d’achats ni consommer un repas. Le cycle complet modifie les données d’un foyer de test.',action:'Teste une recette ou toute la bibliothèque. Ouvre les points signalés, enregistre leurs corrections, puis reteste. Le rapport précédent reste un instantané.',next:{href:'/admin/recipes',label:'Corriger une recette'},extra:{href:'/admin',label:'Retour aux réglages'}},
 '/matcher':{title:'Laboratoire Matcher',position:'Outils avancés · Comprendre un rapprochement',logic:'Le moteur utilise le référentiel et les associations validées avant l’IA. Les unités ne se convertissent qu’avec une équivalence connue.',action:'Teste un libellé et lis le chemin suivi. Une proposition à valider n’est pas une association déjà apprise.',next:{href:'/admin/ingredients',label:'Corriger le référentiel'},extra:{href:'/admin/integration',label:'Tester les recettes'}},
 '/matcher/correction':{title:'Corriger une association',position:'Débloquer une vérification des Courses',logic:'L’association indique quel ingrédient représente le libellé. Elle ne crée pas une conversion de quantité.',action:'Choisis le bon ingrédient officiel et enregistre. Corrige séparément l’unité si nécessaire, puis recalcule les courses.',next:{href:'/courses',label:'Retour aux Courses'},extra:{href:'/admin/ingredients',label:'Voir les équivalences'}},
}
export function screenHelp(pathname:string):ScreenHelp|null{return SCREEN_HELP[pathname==='/point-frigo'?'/inventaire':pathname]||null}
