'use client'
import {useEffect,useRef,useState} from 'react'
import {fefoOrder,stockContent} from '../utils/ecosystem-policy'
import type {HouseholdStockItem} from '../utils/household-server'
type Lot=HouseholdStockItem&{location_name?:string};
type Location={id:string;source:'frosti'|'cellio';name:string};
type Output={produit:string;categorie:string;qte:string;unite:string;location:string;ingredient_id:string;content:string;content_unit:string;date:string;date_role:string;portions:string};
const blank=():Output=>({produit:'',categorie:'Préparations maison',qte:'1',unite:'portion(s)',location:'',ingredient_id:'',content:'',content_unit:'g',date:'',date_role:'unknown',portions:'1'});
const dateLabels:Record<string,string>={dlc:'DLC',ddm:'DDM',indicative:'Date indicative',apogee:'Apogée',unknown:'Date de suivi'};
const field='min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-slate-900';
const button='min-h-11 rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50';
export default function Ecosystem(){
 const [kind,setKind]=useState<'transfer'|'preparation'>('transfer'),[stock,setStock]=useState<Lot[]>([]),[locations,setLocations]=useState<Location[]>([]),[jobs,setJobs]=useState<any[]>([]),[ingredients,setIngredients]=useState<any[]>([]),[recipes,setRecipes]=useState<any[]>([]),[selected,setSelected]=useState<Record<string,string>>({}),[target,setTarget]=useState(''),[outputs,setOutputs]=useState<Output[]>([blank()]),[label,setLabel]=useState(''),[recipe,setRecipe]=useState(''),[fabrication,setFabrication]=useState(new Date().toLocaleDateString('en-CA')),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[review,setReview]=useState<any>(null);
 const [plans,setPlans]=useState<any[]>([]),[mealPlan,setMealPlan]=useState(''),[repairTargets,setRepairTargets]=useState<Record<string,string>>({})
 const operation=useRef<string|null>(null);
 async function load(){
  const [s,j]=await Promise.all([fetch('/api/stock',{cache:'no-store'}),fetch('/api/ecosystem',{cache:'no-store'})]);const sd=await s.json(),jd=await j.json();if(!s.ok||!j.ok)throw new Error(sd.error??jd.error);setStock((sd.items??[]).sort(fefoOrder));setLocations(sd.locations??[]);setJobs(jd.jobs??[]);setIngredients(jd.ingredients??[]);setPlans(jd.plans??[]);
 }
 useEffect(()=>{load().catch(e=>setMessage(e.message));fetch('/api/recipes').then(r=>r.json()).then(d=>setRecipes(d.recipes??[])).catch(()=>{})},[]);
 function changeOutput(index:number,key:keyof Output,value:string){setOutputs(rows=>rows.map((r,i)=>i===index?{...r,[key]:value}:r));setReview(null)}
 function preview(){
  try{
   const inputs=Object.entries(selected).filter(([,v])=>Number(v)>0).map(([key,value])=>{const lot=stock.find(i=>`${i.source}:${i.id}`===key)!;if(!lot||Number(value)>lot.qte)throw new Error('Quantité supérieure au stock.');return {id:lot.id,source:lot.source,amount:Number(value),version:lot.version}});
   const dest=locations.find(l=>`${l.source}:${l.id}`===target);
   if(kind==='transfer'&&(!dest||!inputs.length||inputs.some(i=>i.source===dest.source)))throw new Error('Sélectionnez des articles d’une application et un équipement de l’autre.');
   if(kind==='preparation'&&(!label.trim()||outputs.some(o=>!o.produit.trim()||!o.location||Number(o.qte)<=0)))throw new Error('Nommez la préparation et complétez les lots produits.');
   operation.current=crypto.randomUUID();
   setReview(kind==='transfer'?{kind,operation_id:operation.current,lots:inputs,target_source:dest!.source,target_id:dest!.id}:{kind,operation_id:operation.current,inputs,label:label.trim(),recipe_id:recipe||null,meal_plan_id:mealPlan||null,fabrication_date:fabrication,outputs:outputs.map(o=>({produit:o.produit,categorie:o.categorie,qte:Number(o.qte),unite:o.unite,source:locations.find(l=>`${l.source}:${l.id}`===o.location)!.source,location_id:locations.find(l=>`${l.source}:${l.id}`===o.location)!.id,ingredient_id:o.ingredient_id||null,content_quantity:o.content?Number(o.content):null,content_unit:o.content?o.content_unit:null,date_peremption:o.date||null,date_role:o.date?o.date_role:'unknown',portions:'1'}))});setMessage('');
  }catch(e){setMessage(e instanceof Error?e.message:'Vérifiez les informations.')}
 }
 async function submit(payload:any){
  setBusy(true);try{const response=await fetch('/api/ecosystem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);setReview(null);setSelected({});setMessage('Opération terminée. Le stock et le journal sont actualisés.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Opération interrompue.');await load().catch(()=>{})}finally{setBusy(false)}
 }
 const chosen=Object.entries(selected).filter(([,v])=>Number(v)>0);
 return <main className="mx-auto max-w-4xl space-y-5 px-3 py-6 pb-28"><h1 className="text-2xl font-black">Écosystème</h1><p className="text-slate-600">Transférer des stocks et enregistrer ce que vous avez réellement préparé.</p>
 {message&&<p role="status" className="rounded-xl border bg-white p-4">{message}</p>}
 <div className="flex gap-2"><button className={kind==='transfer'?button:field} onClick={()=>{setKind('transfer');setReview(null);setSelected({})}}>Transfert</button><button className={kind==='preparation'?button:field} onClick={()=>{setKind('preparation');setReview(null);setSelected({})}}>Préparation maison</button></div>
 {!review?<><section className="space-y-3 rounded-2xl border bg-white p-4"><h2 className="text-lg font-bold">{kind==='transfer'?'1. Articles à déplacer':'1. Ingrédients réellement utilisés'}</h2><p className="text-sm text-slate-600">Les dates de suivi les plus proches sont proposées en premier ; les anciennes dates non qualifiées restent signalées comme dates de suivi. Les apogées sont exclues de cet ordre. Les quantités restent exprimées dans l’unité du stock ; 0,5 pot signifie la moitié du contenu déclaré.</p><input aria-label="Rechercher dans le stock" placeholder="Rechercher un produit, un ingrédient…" value={query} onChange={e=>setQuery(e.target.value)} className={field}/>
 <div className="max-h-96 space-y-2 overflow-y-auto">{stock.filter(l=>l.qte>0&&`${l.produit} ${l.ingredient_name??''}`.toLowerCase().includes(query.toLowerCase())).map(l=>{const key=`${l.source}:${l.id}`,total=stockContent(l);return <div key={key} className="rounded-xl border p-3"><p className="font-bold">{l.produit}</p><p className="text-sm text-slate-600">{l.source} · {l.location_name??'Équipement'} · {l.qte} {l.unite}{l.content_quantity?` · ${total.qte} ${total.unite} au total`:''}{l.date_peremption?` · ${dateLabels[l.date_role??'unknown']} : ${new Date(l.date_peremption+'T12:00:00').toLocaleDateString('fr-FR')}`:''}</p><label className="mt-2 block text-sm">{kind==='transfer'?'À transférer':'Utilisé'} ({l.unite})<input className={field} type="number" min="0" max={l.qte} step="any" value={selected[key]??''} onChange={e=>{setSelected({...selected,[key]:e.target.value});setReview(null)}}/></label></div>})}</div><p className="text-sm">{chosen.length} lot(s) sélectionné(s)</p></section>
 {kind==='transfer'?<section className="space-y-3 rounded-2xl border bg-white p-4"><h2 className="text-lg font-bold">2. Équipement de destination</h2><select aria-label="Équipement de destination" value={target} onChange={e=>setTarget(e.target.value)} className={field}><option value="">Choisir…</option>{locations.map(l=><option key={`${l.source}:${l.id}`} value={`${l.source}:${l.id}`}>{l.source} · {l.name}</option>)}</select></section>:<section className="space-y-4 rounded-2xl border bg-white p-4"><h2 className="text-lg font-bold">2. Préparation et lots réellement produits</h2><label className="block">Recette Cookiwiki (facultatif)<select className={field} value={recipe} onChange={e=>{setRecipe(e.target.value);setMealPlan('');setReview(null);const r=recipes.find(r=>r.id===e.target.value);if(r){setLabel(r.nom);setOutputs(rows=>rows.map((o,i)=>i===0?{...o,produit:r.nom}:o))}}}><option value="">Préparation libre</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.nom}</option>)}</select></label>
 {recipe&&<label className="block">Repas du planning (facultatif)<select className={field} value={mealPlan} onChange={e=>{setMealPlan(e.target.value);setReview(null)}}><option value="">Préparation pour plus tard</option>{plans.filter(p=>p.recipe_id===recipe).map(p=><option key={p.id} value={p.id}>{p.scheduled_date} · {p.meal_type} · {p.servings} portions</option>)}</select><span className="text-sm text-slate-600">Ce repas utilisera les lots préparés, sans déduire une deuxième fois leurs ingrédients.</span></label>}
 {recipe&&<div className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">Ingrédients de la recette — à confirmer selon votre réalisation</p>{(recipes.find(r=>r.id===recipe)?.ingredients??[]).map((i:any,n:number)=><p key={n}>{i.qty??i.quantite??''} {i.unit??i.unite??''} · {i.name??i.nom??''}</p>)}<p className="mt-2">La recette ne déduit aucun stock automatiquement. Sélectionnez ci-dessus les lots et quantités réellement utilisés.</p></div>}
 <label className="block">Nom de la préparation<input className={field} value={label} onChange={e=>setLabel(e.target.value)}/></label><label className="block">Date de fabrication<input className={field} type="date" value={fabrication} onChange={e=>setFabrication(e.target.value)}/></label>
 {outputs.map((o,index)=><div key={index} className="space-y-3 rounded-xl border p-3"><h3 className="font-bold">Lot produit {index+1}</h3><label className="block">Produit<input className={field} value={o.produit} onChange={e=>changeOutput(index,'produit',e.target.value)}/></label><label className="block">Catégorie<input className={field} value={o.categorie} onChange={e=>changeOutput(index,'categorie',e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label>Quantité<input className={field} type="number" step="any" min="0.001" value={o.qte} onChange={e=>changeOutput(index,'qte',e.target.value)}/></label><label>Unité<input className={field} value={o.unite} onChange={e=>changeOutput(index,'unite',e.target.value)}/></label></div>{recipe&&<label className="block">Portions par unité produite<input className={field} type="number" min="0.001" step="any" value={o.portions} onChange={e=>changeOutput(index,'portions',e.target.value)}/><span className="text-sm">Exemple : 1 barquette = 2 portions. Cette quantité sera utilisée lors de la confirmation du repas.</span></label>}<label className="block">Rangement<select className={field} value={o.location} onChange={e=>changeOutput(index,'location',e.target.value)}><option value="">Choisir…</option>{locations.map(l=><option key={`${l.source}:${l.id}`} value={`${l.source}:${l.id}`}>{l.source} · {l.name}</option>)}</select></label>
 <details><summary className="cursor-pointer py-2 font-bold">Ingrédient, contenu et date (facultatifs)</summary><div className="space-y-3"><label className="block">Ingrédient officiel<select className={field} value={o.ingredient_id} onChange={e=>changeOutput(index,'ingredient_id',e.target.value)}><option value="">Non associé</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.nom}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>Contenu par unité<input className={field} type="number" step="any" min="0.001" value={o.content} onChange={e=>changeOutput(index,'content',e.target.value)}/></label><label>Unité du contenu<select className={field} value={o.content_unit} onChange={e=>changeOutput(index,'content_unit',e.target.value)}>{['g','mL','pièce(s)'].map(u=><option key={u}>{u}</option>)}</select></label></div><label className="block">Date de suivi<input className={field} type="date" value={o.date} onChange={e=>changeOutput(index,'date',e.target.value)}/></label><label className="block">Rôle de la date<select className={field} value={o.date_role} onChange={e=>changeOutput(index,'date_role',e.target.value)}><option value="unknown">Non précisé</option><option value="dlc">DLC</option><option value="ddm">DDM</option><option value="indicative">Date indicative</option></select></label></div></details>
 {outputs.length>1&&<button className="min-h-11 font-bold text-red-700" onClick={()=>setOutputs(rows=>rows.filter((_,i)=>i!==index))}>Retirer ce lot</button>}</div>)}<button className={field} disabled={outputs.length>=20} onClick={()=>setOutputs([...outputs,blank()])}>+ Ajouter un lot produit</button></section>}
 <button className={button} disabled={busy} onClick={preview}>Vérifier avant confirmation</button></>:<section className="space-y-4 rounded-2xl border bg-white p-4"><h2 className="text-lg font-bold">Confirmer l’opération</h2><p>Ces quantités seront retirées du stock :</p>{chosen.length?chosen.map(([key,value])=>{const l=stock.find(l=>`${l.source}:${l.id}`===key)!;return <p key={key}>{l.produit} : {value} {l.unite} · {l.source}</p>}):<p>Aucun ingrédient sélectionné. Vous confirmez uniquement la production.</p>}
 <p className="font-bold">{kind==='transfer'?`Destination : ${locations.find(l=>`${l.source}:${l.id}`===target)?.name}`:`Production : ${outputs.map(o=>`${o.qte} ${o.unite} de ${o.produit}`).join(', ')}`}</p><p className="text-sm text-slate-600">En cas d’interruption, reprenez cette opération dans le journal ci-dessous. Elle conserve son identifiant et les étapes déjà appliquées.</p><div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>submit(review)}>{busy?'Enregistrement…':'Confirmer'}</button><button disabled={busy} className={field+' w-auto'} onClick={()=>setReview(null)}>Modifier</button></div></section>}
 <section className="space-y-3 rounded-2xl border bg-white p-4"><h2 className="text-lg font-bold">Journal des opérations</h2>{!jobs.length&&<p>Aucune opération.</p>}{jobs.map(j=><div key={j.id} className="rounded-xl border p-3"><p className="font-bold">{j.result?.label??j.result?.recipe_nom??({transfer:'Transfert',preparation:'Préparation',consumption:'Consommation'} as any)[j.kind]}</p><p>{({pending:'À reprendre',processing:'En cours ou à reprendre',blocked:'Interrompue',completed:'Terminée'} as any)[j.status]}</p>{j.error&&<p className="break-words text-sm text-red-700">{j.error}</p>}<p className="text-sm text-slate-600">{j.completed_steps??0} étape(s) confirmée(s) sur {j.actions?.length??'—'}. Une réponse perdue sera vérifiée à la reprise.</p>{j.status!=='completed'&&<button className={button+' mt-2'} disabled={busy} onClick={()=>submit({action:'resume',id:j.id})}>Reprendre l’opération</button>}<details><summary className="cursor-pointer py-2 text-sm">Voir les quantités et les étapes</summary>{(j.actions??[]).map((a:any,index:number)=>{const done=j.status==='completed'||index<Number(j.completed_steps??0);const key=`${j.id}:${index}`;return <div key={index} className="my-3 rounded-lg border p-2"><p>{done?'Effectué':'Prévu / à vérifier'} : {a.action==='add'?'rangement':'déduction'} · {a.payload?.produit??a.item_id} · {a.payload?.qte??a.payload?.amount} {a.payload?.unite??''} · {a.source}</p>{!done&&a.action==='add'&&<label className="mt-2 block text-sm">Corriger la destination<select className={field} value={repairTargets[key]??''} onChange={e=>setRepairTargets({...repairTargets,[key]:e.target.value})}><option value="">Choisir un équipement de {a.source}…</option>{locations.filter(l=>l.source===a.source).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button className={button+' mt-2'} disabled={busy||!repairTargets[key]} onClick={()=>submit({action:'repair_destination',id:j.id,index,target_id:repairTargets[key]})}>Corriger et reprendre</button></label>}</div>})}{(j.result?.consumed??[]).map((i:any,n:number)=><p key={n}>{j.status==='completed'?'Utilisé':'Utilisation prévue'} : {i.qte} {i.unite} · {i.produit} ({i.source})</p>)}{(j.result?.outputs??[]).map((i:any,n:number)=><p key={n}>{j.status==='completed'?'Rangé':'Rangement prévu'} : {i.qte} {i.unite} · {i.produit} ({i.source})</p>)}</details></div>)}</section>
 </main>
}
