-- Projet SUPABASE MEALIO. Exécuter après la migration 1.2.4 et avant le code 1.2.5.
-- Formats proposés, modifiables. Ce ne sont pas des densités.
BEGIN;
CREATE TABLE IF NOT EXISTS public.pantry_products (
  ingredient_id uuid PRIMARY KEY REFERENCES public.official_ingredients(id) ON DELETE CASCADE,
  default_quantity numeric NOT NULL CHECK (default_quantity > 0 AND default_quantity::text NOT IN ('NaN','Infinity','-Infinity')),
  default_unit text NOT NULL CHECK (length(trim(default_unit)) > 0),
  enabled boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.pantry_products ENABLE ROW LEVEL SECURITY;
-- Accès via les routes serveur authentifiées Mealio (service key), pas via le navigateur.
ALTER TABLE public.shopping_items ADD COLUMN IF NOT EXISTS pantry_pack_quantity numeric
  CHECK (pantry_pack_quantity IS NULL OR (pantry_pack_quantity > 0 AND pantry_pack_quantity::text NOT IN ('NaN','Infinity','-Infinity')));

WITH defaults(nom, quantity, unit) AS (VALUES
  ('Algue nori', 25, 'Gramme'),
  ('Champignon séché', 30, 'Gramme'),
  ('Levure de bière', 250, 'Gramme'),
  ('Pâte de curry', 250, 'Gramme'),
  ('Pâte miso', 250, 'Gramme'),
  ('Sauce tomate cuisinée', 250, 'Millilitre'),
  ('Lait de coco', 400, 'Millilitre'),
  ('Abricot sec', 250, 'Gramme'),
  ('Amande', 250, 'Gramme'),
  ('Cacahuète', 250, 'Gramme'),
  ('Datte séchée', 250, 'Gramme'),
  ('Figue séchée', 250, 'Gramme'),
  ('Graine de courge', 250, 'Gramme'),
  ('Graine de lin', 250, 'Gramme'),
  ('Graine de sésame', 250, 'Gramme'),
  ('Graine de tournesol', 250, 'Gramme'),
  ('Noisette', 250, 'Gramme'),
  ('Noix', 250, 'Gramme'),
  ('Noix de cajou', 250, 'Gramme'),
  ('Noix de pécan', 250, 'Gramme'),
  ('Pignon de pin', 250, 'Gramme'),
  ('Pistache', 250, 'Gramme'),
  ('Pruneau sec', 250, 'Gramme'),
  ('Raisin sec', 250, 'Gramme'),
  ('Blé (grain)', 500, 'Gramme'),
  ('Boulgour', 500, 'Gramme'),
  ('Couscous / Semoule', 500, 'Gramme'),
  ('Farine de blé', 1000, 'Gramme'),
  ('Farine de sarrasin', 1000, 'Gramme'),
  ('Flocons d''avoine', 500, 'Gramme'),
  ('Maïzena', 250, 'Gramme'),
  ('Polenta', 500, 'Gramme'),
  ('Pâtes (coquillettes)', 500, 'Gramme'),
  ('Pâtes (penne)', 500, 'Gramme'),
  ('Pâtes (spaghetti)', 500, 'Gramme'),
  ('Pâtes (tagliatelle)', 500, 'Gramme'),
  ('Quinoa', 500, 'Gramme'),
  ('Riz basmati', 500, 'Gramme'),
  ('Riz complet', 500, 'Gramme'),
  ('Riz rond', 500, 'Gramme'),
  ('Semoule fine', 500, 'Gramme'),
  ('Haricot blanc (sec)', 500, 'Gramme'),
  ('Haricot rouge (sec)', 500, 'Gramme'),
  ('Lentille corail', 500, 'Gramme'),
  ('Lentille verte', 500, 'Gramme'),
  ('Pois cassé', 500, 'Gramme'),
  ('Pois chiche', 500, 'Gramme'),
  ('Huile d''olive', 750, 'Millilitre'),
  ('Huile de colza', 750, 'Millilitre'),
  ('Huile de sésame', 250, 'Millilitre'),
  ('Huile de tournesol', 750, 'Millilitre'),
  ('Biscotte', 250, 'Gramme'),
  ('Chapelure', 250, 'Gramme'),
  ('Bouillon cube (bœuf)', 10, 'Pièce'),
  ('Bouillon cube (légumes)', 10, 'Pièce'),
  ('Bouillon cube (volaille)', 10, 'Pièce'),
  ('Concentré de tomate', 70, 'Gramme'),
  ('Cornichon (condiment)', 250, 'Gramme'),
  ('Coulis de tomate', 500, 'Millilitre'),
  ('Câpre', 250, 'Gramme'),
  ('Ketchup', 250, 'Gramme'),
  ('Moutarde', 250, 'Gramme'),
  ('Olive noire', 250, 'Gramme'),
  ('Olive verte', 250, 'Gramme'),
  ('Sauce nuoc-mâm', 250, 'Millilitre'),
  ('Sauce soja', 250, 'Millilitre'),
  ('Sauce sriracha', 250, 'Millilitre'),
  ('Sauce worcestershire', 150, 'Millilitre'),
  ('Tabasco', 60, 'Gramme'),
  ('Tomate pelée (boîte)', 400, 'Gramme'),
  ('Vinaigre balsamique', 500, 'Millilitre'),
  ('Vinaigre blanc', 500, 'Millilitre'),
  ('Vinaigre de cidre', 500, 'Millilitre'),
  ('Cacao en poudre', 250, 'Gramme'),
  ('Cassonade', 1000, 'Gramme'),
  ('Chocolat au lait', 200, 'Gramme'),
  ('Chocolat blanc', 200, 'Gramme'),
  ('Chocolat noir', 200, 'Gramme'),
  ('Confiture', 250, 'Gramme'),
  ('Extrait de vanille', 20, 'Gramme'),
  ('Gélatine (feuille)', 6, 'Gramme'),
  ('Levure boulangère', 7, 'Gramme'),
  ('Levure chimique', 11, 'Gramme'),
  ('Miel', 250, 'Gramme'),
  ('Poudre d''amande', 250, 'Gramme'),
  ('Pépites de chocolat', 200, 'Gramme'),
  ('Sirop d''érable', 250, 'Gramme'),
  ('Sucre en poudre', 1000, 'Gramme'),
  ('Sucre glace', 1000, 'Gramme'),
  ('Sucre roux', 1000, 'Gramme'),
  ('Vanille (gousse)', 2, 'Gousse'),
  ('Ail en poudre', 25, 'Gramme'),
  ('Baies roses', 25, 'Gramme'),
  ('Basilic séché', 25, 'Gramme'),
  ('Cannelle', 25, 'Gramme'),
  ('Cardamome', 25, 'Gramme'),
  ('Cinq-épices', 25, 'Gramme'),
  ('Cumin', 25, 'Gramme'),
  ('Curcuma', 25, 'Gramme'),
  ('Curry (poudre)', 25, 'Gramme'),
  ('Gingembre en poudre', 25, 'Gramme'),
  ('Herbes de Provence', 25, 'Gramme'),
  ('Muscade', 25, 'Gramme'),
  ('Origan séché', 25, 'Gramme'),
  ('Paprika', 25, 'Gramme'),
  ('Piment d''Espelette', 25, 'Gramme'),
  ('Piment de Cayenne', 25, 'Gramme'),
  ('Poivre blanc', 250, 'Gramme'),
  ('Poivre noir', 250, 'Gramme'),
  ('Safran', 1, 'Gramme'),
  ('Sel fin', 250, 'Gramme'),
  ('Sel gros / Fleur de sel', 250, 'Gramme'),
  ('Thym séché', 25, 'Gramme')
)
INSERT INTO public.pantry_products (ingredient_id, default_quantity, default_unit)
SELECT o.id, d.quantity, d.unit
FROM defaults d JOIN public.official_ingredients o ON o.nom = d.nom
ON CONFLICT (ingredient_id) DO NOTHING;
-- Les réexécutions préservent tes quantités personnalisées et les modes désactivés.
COMMIT;

SELECT o.nom, p.default_quantity, p.default_unit, p.enabled
FROM public.pantry_products p JOIN public.official_ingredients o ON o.id=p.ingredient_id
ORDER BY o.nom;
